#!/usr/bin/env python3

import requests
import argparse
import bs4

# Console control
parser = argparse.ArgumentParser(prog='Simplify', description='Get description of the word')
parser.add_argument("word", help="type a word to get its definition", type=str) 
args = parser.parse_args()

# Web scraping
dictionary_url = "https://www.merriam-webster.com/dictionary/"
request_url = dictionary_url + args.word
data = requests.get(request_url)

# Creating BeautifulSoup instance
soup = bs4.BeautifulSoup(data.content, 'html.parser')

# Finding main definition containers
parent_vg = soup.find_all("div", attrs={"class": "vg"})

# Handling definition containers
definitions:list[list[tuple[str, str]]] = [] 
temp_container = []
for child_dt in parent_vg[0].find_all('span', attrs={'class': 'dt'}):
    for element in child_dt: 
        if isinstance(element, bs4.element.Tag):
            if element.attrs['class'][0] == 'dtText':
                main_check = True
                temp_container.append(element.text)
            elif element.attrs['class'][0] == 'sub-content-thread':
                temp_container.append(element.text)
    definitions.append(tuple(temp_container))
    temp_container = [] 

# Making output cool for console output
for line_num, content in enumerate(definitions, 1):
    print(f"{line_num} {content[0]}")
    if len(content) > 1:
        print(f"\t{content[-1]}")
    print("")
